### ISSUE TITLE
Update pycodestyle for flake8

### ISSUE THREAD

**Issue by wdv4758h** [wdv4758h/python-everywhere#1]
`pep8` is the original Python style guide checker used by `flake8`, but it has been renamed to `pycodestyle`. We should integrate `flake8` with the new one :)
- https://github.com/PyCQA/pycodestyle 
- https://github.com/PyCQA/pycodestyle/issues/466

**Comment by hugovk** [comment]
I think this can be closed, `flake8` now uses `pycodestyle`:

```
$ pip install -U flake8
Requirement already up-to-date: flake8 in /usr/local/lib/python2.7/site-packages
Requirement already up-to-date: pycodestyle<2.4.0,>=2.0.0 in /usr/local/lib/python2.7/site-packages (from flake8)
Requirement already up-to-date: enum34; python_version < "3.4" in /usr/local/lib/python2.7/site-packages (from flake8)
Requirement already up-to-date: configparser; python_version < "3.2" in /usr/local/lib/python2.7/site-packages (from flake8)
Requirement already up-to-date: pyflakes<1.6.0,>=1.5.0 in /usr/local/lib/python2.7/site-packages (from flake8)
Requirement already up-to-date: mccabe<0.7.0,>=0.6.0 in /usr/local/lib/python2.7/site-packages (from flake8)
```

**Comment by wdv4758h** [comment]
@hugovk Ha ha, I didn't update this repo for a long time. It suprises me that someone will leave a comment 😃

**Comment by hugovk** [comment]
I found it linked from PyCQA/pycodestyle#466 :)

**Comment by wdv4758h** [comment]
Notice from the link, there are still lots of project with related issue opened out there. 😛  @hugovk thanks, you make me wanna spend some time update this repo.
